coverage:
  notify:
    slack:
      default:
        url: "secret:2e9vXpE39naCdLS6Hw+hH65E3bpm1Z3OiRrnsNl8shwsscnddHpJD7i6YSe1BZFNJ7MRgWNBK9RPpWdNbJjGvDUcg2oqRJFy1qQrTAVnjvILvdOvZfcmsEWCWRyoz9JBIMOe6L8NqnpcXF9O0N9HMrulo6bhV9jbHXxm5eJA/wI="
        threshold: 0.0%
